import { Geist, Geist_Mono } from "next/font/google";
import "../global.css";
import Workcontext from "@/context/Workcontext";
import Rdxpr from "@/reduxstore/Rdxpr";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    template: "%s | Next.js App",
    default: "Next.js App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const rendome = Math.random();
  // console.log(rendome);

  // if (rendome > 0.5) {
  //   throw new Error("This is a random error for testing purposes.");
  // }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Workcontext>
          <Rdxpr>{children}</Rdxpr>{" "}
        </Workcontext>
      </body>
    </html>
  );
}
